baseURL = "https://blog.adamvig.com"
disableKinds = ["section", "taxonomy", "term"]
enableRobotsTXT = true
languageCode = "en-us"
paginate = 25

title = "Blog — Adam Vigneaux"

[params]
	description = "The blog of Adam Vigneaux, a software developer located in Texas."

[minify]
  minifyOutput = true
